version: '3.8'

services:
  app:
    image: nginx:1.25-alpine
    container_name: app_memoire_container
    ports:
      - "8888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www/html
      - ./php-fpm.conf:/etc/nginx/conf.d/php-fpm.conf:ro
    depends_on:
      - php
      - db
    networks:
      - monitoring

  php:
    image: php:8.2-fpm-alpine
    container_name: php_fpm
    volumes:
      - .:/var/www/html
    environment:
      PHP_MEMORY_LIMIT: 256M
    networks:
      - monitoring

  db:
    image: mysql:5.7
    container_name: db_memoire
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: app_pass
      MYSQL_DATABASE: demandegrace
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./demandegrace.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring

volumes:
  db_data:

networks:
  monitoring:
    driver: bridge