version: '3.8'

services:
  app:
    build: .
    container_name: app_memoire_container
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db_memoire
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: app_pass
      MYSQL_DATABASE: app_memoire_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: